name: Release Prepare to PyPi

on:
  push:
    branches:
      - 'releases/**'
    tags:
      - 'v*'

jobs:
  release:
    strategy:
        matrix:
          python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # No cache for releases (the default for tag pushes), to prevent cache poisoning
      - name: Install uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
