name: Test

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --group test
    - name: Setup git
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.ACTIONS_DEPLOY_KEY }}
          ${{ SECRETS.ACTIONS_COMPOSITE_KEY }}
          ${{ SECRETS.ACTIONS_CODESTRIPPER_KEY }}
    - name: Run tests
      run: uv run pytest --cov --cov-report=xml --junitxml=tests.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (Python version ${{ matrix.python-version }})
        path: tests.xml
        reporter: java-junit

  typecheck:
    strategy:
      matrix:
        python-version: [ "3.9" ]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group test
      - name: Type checker
        run: uv run mypy prepare_assignment
